// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Simple_Debugger_Display_Helper
{
    internal sealed partial class Vsix
    {
        public const string Id = "Simple_Debugger_Display_Helper.cb9420fb-6953-4da8-8c3f-07cc62e1feb7";
        public const string Name = "Simple Debugger Display Helper";
        public const string Description = @"A simple Visual Studio 2022 extension that will help you add items to a class’s Debugger Display attribute.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Thomas (TJ) Wills";
        public const string Tags = "";
    }
}
