// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Simple_Debugger_Display_Helper
{
    internal sealed partial class Vsix
    {
        public const string Id = "Simple_Debugger_Display_Helper.cb9420fb-6953-4da8-8c3f-07cc62e1feb7";
        public const string Name = "Simple_Debugger_Display_Helper";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Microsoft";
        public const string Tags = "";
    }
}
