// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Simple_Debugger_Display_Helper
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string Simple_Debugger_Display_HelperString = "5f870cbc-2683-43e2-8ed2-be085921277f";
        public static Guid Simple_Debugger_Display_Helper = new Guid(Simple_Debugger_Display_HelperString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int AddToDebuggerDisplay = 0x0100;
    }
}